/**
 * Network related action types
 *
 */

export const REQUEST_BEGIN = 'REQUEST_BEGIN';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILED = 'REQUEST_FAILED';

export const LOGIN_REQUEST_BEGIN = 'LOGIN_REQUEST_BEGIN';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILED = 'LOGIN_REQUEST_FAILED';

export const REGISTER_REQUEST_BEGIN = 'REGISTER_REQUEST_BEGIN';
export const REGISTER_REQUEST_SUCCESS = 'REGISTER_REQUEST_SUCCESS';
export const REGISTER_REQUEST_FAILED = 'REGISTER_REQUEST_FAILED';

export const PROFILES_REQUEST_BEGIN = 'PROFILES_REQUEST_BEGIN';
export const PROFILES_REQUEST_SUCCESS = 'PROFILES_REQUEST_SUCCESS';
export const PROFILES_REQUEST_FAILED = 'PROFILES_REQUEST_FAILED';